name: Feature
description: Create a new Feature item
labels:
  - 🚀 Feature
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        
        Please fill in the details below to describe the new feature.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Briefly describe the value of this feature."
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: "What is included? What is not?"
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies (Optional)
      description: |
        Add any relevant dependencies.
    validations:
      required: false
