name: Feature
description: Create a new Feature item
title: "[Feature]: "
labels: ["feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Title

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Briefly describe the value of this feature.
      placeholder: e.g., "Allow users to filter products by category"
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is included? What is not?
      placeholder: In scope: UI component; Out of scope: backend API
    validations:
      required: false

  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies (if any)
      options:
        - label: Dependency 1
        - label: Dependency 2
        - label: Dependency 3
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any relevant details, context, or links.
      placeholder: e.g., Related ticket: #123, Design mockup URL, etc.
    validations:
      required: false
