name: Feature
description: Create a new Feature item
labels:
  - 🚀 Feature
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request

        Please fill in the details below to describe the new feature.

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: "Briefly describe the value of this feature."
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: "What is included? What is not?"
    validations:
      required: false

   - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies (Editable)
      description: Dependencies (if any)
         
      options:
        - label: "[ ] Dependency 1 (edit me)"
        - label: "[ ] Dependency 2 (edit me)"
        - label: "[ ] Dependency 3 (edit me)"
