name: Feature
description: Create a new Feature item
title: Feature Request
labels:
  - feature
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request

        Please fill in the details below to describe the new feature.

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: "Briefly describe the value of this feature."
      placeholder: "e.g., Allow users to filter products by category."
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: "What is included? What is not?"
      placeholder: "e.g., In scope: UI filters; Out of scope: backend APIs."
    validations:
      required: false

  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies (if any)
      options:
        - label: "Dependency 1"
