name: OKR
description: Create a new Objective & Key Results item
labels:
  - 🎯 OKR

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 OKR Title
        Add a concise title for the OKR.

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: "Enter the objective details here."
    validations:
      required: true

  - type: textarea
    id: key_results
    attributes:
      label: Key Results (Optional)
      description: |
        Enter one key result per line. You can use markdown checkboxes:
        - [ ] Example key result
    validations:
      required: false
