name: Story
description: Create a new Story
labels:
  - 📘 Story

body:
  - type: markdown
    attributes:
      value: |
         Please fill in the details below to describe the story.



  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A brief description of the user story and what it’s intended to achieve."
    validations:
      required: true
