name: Task
description: Create a new Task
labels:
  - 🔧 Task

body:
  - type: markdown
    attributes:
      value: |
        ## 🔧 Task Title
        Add a concise title for the Task.

  - type: textarea
    id: task_list
    attributes:
      label: Task List (Optional)
      description: "Add tasks or subtasks using markdown checkboxes. You can add new items by typing below."
    validations:
      required: false
